// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcrtdyfltMwwCHA4XRqRiJHqFxk4hSVvs',
    appId: '1:446708096885:web:e653cc79784a8040e57d3c',
    messagingSenderId: '446708096885',
    projectId: 'client-salloon',
    authDomain: 'client-salloon.firebaseapp.com',
    storageBucket: 'client-salloon.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfsXNMukbTn3o_cL3lirZ3jpuXiLK2yzg',
    appId: '1:446708096885:android:fae70d728e9bb1d1e57d3c',
    messagingSenderId: '446708096885',
    projectId: 'client-salloon',
    storageBucket: 'client-salloon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnO2wm6_j-o97cn7A5MJWI4PPSXArs-EY',
    appId: '1:446708096885:ios:cefdeb56c33f9999e57d3c',
    messagingSenderId: '446708096885',
    projectId: 'client-salloon',
    storageBucket: 'client-salloon.appspot.com',
    iosBundleId: 'com.example.saloonApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnO2wm6_j-o97cn7A5MJWI4PPSXArs-EY',
    appId: '1:446708096885:ios:cefdeb56c33f9999e57d3c',
    messagingSenderId: '446708096885',
    projectId: 'client-salloon',
    storageBucket: 'client-salloon.appspot.com',
    iosBundleId: 'com.example.saloonApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcrtdyfltMwwCHA4XRqRiJHqFxk4hSVvs',
    appId: '1:446708096885:web:407abdb1da391fdde57d3c',
    messagingSenderId: '446708096885',
    projectId: 'client-salloon',
    authDomain: 'client-salloon.firebaseapp.com',
    storageBucket: 'client-salloon.appspot.com',
  );

}